version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: hms-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api-gateway:8080
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: hms-api-gateway
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - CORE_APP_URL=http://app-monolith:5000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3020
      - BILLING_SERVICE_URL=http://billing-service:3011
      - PRESCRIPTION_SERVICE_URL=http://prescription-service:3012
      - INSURANCE_SERVICE_URL=http://insurance-service:3013
    depends_on:
      - app-monolith
      - appointment-service
      - billing-service
      - prescription-service
      - insurance-service

  redis:
    image: redis:7-alpine
    container_name: hms-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  notification-service:
    build: ./notification-service
    container_name: hms-notification-service
    restart: unless-stopped
    ports:
      - '3010:3010'
    environment:
      - PORT=3010
      - RESEND_API_KEY=${RESEND_API_KEY}
      - REDIS_URL=redis://redis:6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - redis
      - kafka

  app-monolith:
    build: .
    container_name: hms-monolith
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - redis
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

  appointment-service:
    build: ./appointment-service
    container_name: hms-appointment-service
    restart: unless-stopped
    ports:
      - '3020:3020'
    environment:
      - PORT=3020
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL_APPOINTMENT_DOCKER}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

  billing-service:
    build: ./billing-service
    container_name: hms-billing-service
    restart: unless-stopped
    ports:
      - '3011:3011'
    environment:
      - PORT=3011
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL_BILLING_DOCKER}
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3020
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
      - kafka
      - app-monolith
      - appointment-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prescription-service:
    build: ./prescription-service
    container_name: hms-prescription-service
    restart: unless-stopped
    ports:
      - '3012:3012'
    environment:
      - PORT=3012
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL_PRESCRIPTION_DOCKER}
      - CORE_APP_URL=http://app-monolith:5000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3020
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - kafka
      - app-monolith
      - appointment-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  insurance-service:
    build: ./insurance-service
    container_name: hms-insurance-service
    restart: unless-stopped
    ports:
      - '3013:3013'
    environment:
      - PORT=3013
      - DATABASE_URL=${DATABASE_URL_INSURANCE_DOCKER}
      - CORE_APP_URL=http://app-monolith:5000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3020
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - kafka
      - app-monolith
      - appointment-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: hms-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

volumes:
  redis_data:

